### ISSUE TITLE
I can delete cache

### ISSUE THREAD

**Issue by nguyenvanquan7826** [gurayyarar/AdminBSBMaterialDesign#29]
Hi, thank for your product. I use it but when I change some style in css, It not change in my browser if I not use incognito. So my visitor also see my change. Please help me to delete cache. Thank you

**Comment by gurayyarar** [comment]
Hi, because of your browser cache. It will be also for js files. When you change the css or js file please add or update version number end of the static files, like this;
`<link href="assets/css/style.css?v=2" rel="stylesheet" />`
`<script src="assets/js/pages/dashboard/dashboard.js?v=50"></script>`

**Comment by nguyenvanquan7826** [comment]
Thank you!
