### ISSUE TITLE
How can i make sidebar hide/show on demand instead of width<1170 px ?

### ISSUE THREAD

**Issue by manenikhil** [gurayyarar/AdminBSBMaterialDesign#4]
Left sidebar hide/show when width goes below 1170 px ? can you please let me know how can i make the left sidebar hide/show on any viewport with help of button / link ?

Thanks

**Comment by gurayyarar** [comment]
Hello,
Sorry for my late answer,

*1)* *index.html* -> Add ls-closed to body element
[image: Satır içi resim 1]

*2) admin.js* -> You can delete this functions. I set as a comment line,
because you can see which line
[image: Satır içi resim 2]

*3) style.css* -> set important this option
[image: Satır içi resim 3]

Now you can show/hide menu with left top side button

[image: Satır içi resim 5]

Thanks.

2016-11-22 10:19 GMT+03:00 manenikhil <notifications@github.com>:

**Comment by manenikhil** [comment]
I am unable to see the attached images in this thread.

Thanks

**Comment by gurayyarar** [comment]
Hello,
I inserted inside the email. Well, i put now on attachment with number



2016-11-23 9:35 GMT+03:00 manenikhil <notifications@github.com>:

**Comment by Jalalx** [comment]
Thank you, man! I was trying to do this by myself, but I failed. I didn't know there is a built-in support for this.

**Comment by diegomaximino** [comment]
Thank you, it worked.

**Comment by andrefantinato** [comment]
Thank you @gurayyarar, it worked for me!

**Comment by sserghei** [comment]
Thank you @gurayyarar !!!

**Comment by sayassyk** [comment]
Savior!! 😍 ❤️ 🥇

**Comment by vmgm87** [comment]
Hello, I tried this...but it did not work :(

**Comment by vmgm87** [comment]
@gurayyarar  can you help me?

**Comment by vmgm87** [comment]
Sorry @gurayyarar  it worked! thanks :D

**Comment by jvbalcita** [comment]
@gurayyarar If I may ask how to make the side bar always active but still the show/hide button is there.
