### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by acool9531** [gurayyarar/AdminBSBMaterialDesign#8]
Hello gurayyarar
first of all i wanna say it's an amazing template!
It is not working on UC browser mobile version.Can you please give possible solution for it or please fix for uc mobile version also.
Thanks for your job!!!

**Comment by gurayyarar** [comment]
Hi,
I tested my Windows Phone 8.1 with UC Browser. It's working. I couldn't see anything. Also i'm putting the screenshot on my phone
![wp_ss_20161205_0001](https://cloud.githubusercontent.com/assets/8344559/20876748/c0c419ec-bacc-11e6-8232-5b84b880e78c.jpg)

**Comment by acool9531** [comment]
Hi,
Thanks for reply.I tested on my android(marshmallow) uc browser.I am putting screenshot for your refrence.
![screenshot_2016-12-08-13-44-20-704_com ucmobile intl](https://cloud.githubusercontent.com/assets/24369778/21002854/e8748502-bd4d-11e6-8cba-fdc18b8b470e.png)
![screenshot_2016-12-08-13-46-16-697_com ucmobile intl](https://cloud.githubusercontent.com/assets/24369778/21002855/e878f8c6-bd4d-11e6-9437-7e7ec41cc98b.png)
![screenshot_2016-12-08-13-50-32-021_com ucmobile intl](https://cloud.githubusercontent.com/assets/24369778/21002856/e886cd3e-bd4d-11e6-83a3-f57816d473e4.png)

**Comment by acool9531** [comment]
Hello, Please check this on safari browser (windows). Its the same problem occured in safari also.
Thankyou.

**Comment by gurayyarar** [comment]
Hi,
On windows safari version, it's normal situation. Because after the year of 2012, safari not supporting for Windows OS. You can check version history on this page which link is https://en.wikipedia.org/wiki/Safari_version_history
![image](https://cloud.githubusercontent.com/assets/8344559/22497356/d4b52918-e859-11e6-9b50-15277b2daf0a.png)

You need to check latest version of safari on MAC or IOS devices.
